# Generated by Django 2.0.13 on 2020-04-15 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=datetime.datetime(2020, 4, 15, 18, 53, 51, 43211, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
    ]
